import math
import torch
import torch.nn as nn



class TokenEmbedding(nn.Module):
    """
    Transform token ids into dense vector. This dense vectors are
    randomly generated by nn.Embedding and will be updated during training
    process.

    This approach is basically indexing the token id into vector.
    For instance, the token id is 4, then nn.Embedding will search vector
    on id 4. This vector then will be updated during training. The vector
    values within this nn.Embedding will be updated using chain rule, where
    the vector value of each token will be updated with the dL/dy.

    W new = W old - (lr * dL/dy)
    
    Return:
        embedding vector with specific size
        example:
        token_idx = [1, 2124, 12312, 12321, 2]
        embedding_vector_dimension = torch.size([5, 768])
    """
    def __init__(self, vocab_size, d_model):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)

    def forward(self, x):
        return self.embedding(x)
    

class PositionalEncoding(nn.Module):
    """
    Adds position information so the transformer knows token order.
    """
    def __init__(self, d_model, max_len=5000):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1)
        div_term = torch.exp(
            torch.arange(0, d_model, 2) *
            (-math.log(10000.0) / d_model)
        )
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.pe = pe.unsqueeze(0)

    def forward(self, x):
        return x + self.pe[:, :x.size(1)]



class MultiHeadAttention(nn.Module):
    """
    Algo detailed explanation:
        1. Multi-head attention dimensional changing
            Change the structure of single head attention to multi-head attention.
            Initial dimension: [batch_size, sequence_length, embedding_dimension]

            The dimensional structure chaning is only applied to q matrix, where the other
            two (k and v) will have initial matrix with head_dim dimension (for inference
            optimization).

            So, each of q, k, and v will have dimension:
            [batch_size, sequence_length, num_heads, head_dim]

            This matrix then is reshaped into [batch_size, num_heads, sequence_length, head_dim]
            because we want to create several attention heads which can understand different contexts

            this matrix then will be multiplied with Wq, Wk, and Wv which each of them has dimension of
            [head_dim, head_dim]

            The output will be matrix Q, K, and V with dimension [batch_size, num_heads, sequence_length, head_dim]

        2. Scaled dot attention
            Matrix Q, K, and V will be calculated through attention formula, including casual attention masking.

            The output of this attention formula (multi heads attention matrix) will then be reshaped into original dimension
            (single head attention matrix) with .view() method in PyTorch.

        3. linear projection with o_proj
            The reshaped matrix (raw attention score) finally passed the linear matrix (o_proj) to grab contextual
            information gathered from each of attention head.

    Result:
        Attention score matrix [batch_size, sequence_length, embedding_dim]
    

    """
    def __init__(self, d_model, num_heads):
        super().__init__()
        # Define variables
        self.num_heads = num_heads
        self.head_dim = d_model // num_heads
        self.q_proj = nn.Linear(d_model, d_model)
        self.k_proj = nn.Linear(d_model, self.head_dim)
        self.v_proj = nn.Linear(d_model, self.head_dim)
        self.out_proj = nn.Linear(d_model, d_model)

    
    def scaled_dot_product_attention(self, Q, K, V):
        """
        Applying scale dot product attention which process Q, K, and V.
        1. Multiply Q and K transpose, then scaling them with square root of head dim
        2. Masking the raw multiplicaton result of Q and KT, then applying softmax.
        3. Softmax will result a matrix with prabability values and 0 values because
        we masked several tokens with -inf
        4. Multiply this result 
        """
        # We will work with multi-head attention, so we need to
        # get head_dim instead of full embedding_vector_size
        head_dim = Q.size(-1)
        sequence_length = Q.size()[-2]
        
        # Calculate raw attention score
        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(head_dim)

        # Casual masking (manual)
        ## Creating base matrix (matrix 1)
        masking_matrix = torch.ones(sequence_length, sequence_length)
        ## Mask diagonal with 0
        masking_matrix = torch.tril(masking_matrix, diagonal=0)
        ## Mask 0 with -inf
        masking_matrix = masking_matrix.masked_fill(masking_matrix == 0, -torch.inf)
        masking_matrix = torch.where(masking_matrix == 1, 0, masking_matrix)
        # Expand to make the dimension the same as attention score matrix
        masking_matrix = masking_matrix.expand(
            scores.size()[0],
            scores.size()[1],
            masking_matrix.size()[0],
            masking_matrix.size()[1]
        )

        # Adding attention score matrix with casual masking matrix
        final_score = torch.add(scores, masking_matrix)

        attention = torch.softmax(final_score, dim=-1)
        output = torch.matmul(attention, V)

        return output


    def forward(self, x):
        B, T, C = x.size()
        # Calculating Q, K, and V (notation with lowercase)
        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)


        # Reshaping into multi-head attention matrix
        q = q.view(B, T, self.num_heads, self.head_dim).transpose(1,2)

        k = k.unsqueeze(2)
        k = k.expand(k.size()[0], k.size()[1], self.num_heads, k.size()[3]).transpose(1,2)

        v = v.unsqueeze(2)
        v = v.expand(v.size()[0], v.size()[1], self.num_heads, v.size()[3]).transpose(1,2)

        # Performing scaled dot attention
        out = self.scaled_dot_product_attention(q, k, v)
        
        # Reshaping raw multi-head attention score matrix
        out = out.transpose(1,2).contiguous().view(B, T, C)

        # Applying linear projection with o_proj
        out = self.out_proj(out)

        return out
    

class FeedForward(nn.Module):
    """
    This layer is applied after we got attention score. Attention score basically
    a matrix which represents the clue or tokens relationship within each sentence.
    This clue is basically represented with linear understanding within attention layer.

    In this FFN layer, we implement non linear activation layer (with GELU) which can capture
    non-linear relationship of the clue from attention layer.

    Result:
        Output matrix with the dimension of [d_model, d_model]
    """
    def __init__(self, d_model, hidden_dim):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(d_model, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, d_model)
        )

    def forward(self, x):
        return self.net(x)